### PR TITLE
Allow build without GUI using GUI=0

### PR DESCRIPTION
**Pull request by AlejandroVera**
Use qmake GUI=0 to generate a Makefile that will build without GUI.

### CODE REVIEW

**Comment by Hyjaz** [comment]
I got a fatal error: `rc/txdb-leveldb.cpp:8:10: fatal error: 'boost/version.hpp' file not found`

Currently checking how I can fix this.

**Comment by AlejandroVera** [comment]
@Hyjaz Probably you are missing some boost dependecies. Make sure that you have the mac equivalent to Linux's `libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev`

**Comment by Hyjaz** [comment]
I was able to run electrad without the GUI.

**Comment by Hyjaz** [comment]
Can you add it in the doc?

**Comment by alediaferia** [comment]
Please, hold off on this change. I'm in the process of re-organizing the project to take advantage of the SUBDIRS feature in qmake in order to make the whole thing more modular.

The core and gui will be split in order to make it easier to run the tests (that are already there) against the core. This will also make it easier to include your change to disable the GUI.

**Comment by alediaferia** [comment]
Hi @AlejandroVera , I have re-applied your same change to the `nogui` branch but if you'd like to rebase and do it on this branch I'd be happy to accept this PR and close the `nogui` branch. Let me know.

**Comment by alediaferia** [comment]
Re-applied in #12 .

**Pull request closed without merging**
